### ISSUE TITLE
Question about what is sent to to openai endpoint?

### ISSUE THREAD

**Issue by porteron** [RobinPicard/metabase-chatgpt#8]
Hello @RobinPicard, question about the `promptMessage` sent in the request to openai:
-  I do not see in the code any indication that the table schema information is sent to openai. So how does openai know what columns are available to include in the query? To me it seems that the only way openai will include a property in the response query is if it was specified in the initial query, otherwise it will be unaware of the other columns. Is this correct?

Thank you, you've done wonderful work here.

**Comment by RobinPicard** [comment]
Hi @porteron!

**Comment by RobinPicard** [comment]
Hi @porteron!

Yes, this is correct. I initially thought it's not really an issue because my use case was to help some colleagues (mainly PMs and ops people) who know the data schema and know some SQL (so they write their own queries) but are sometimes blocked when trying to do something a bit more advanced. In that case, they would typically already have a query that does something related but a little tweak was missing.

Later I realized that I would need to provide this schema information to Openai to broaden the use of this extension but I could not figure out how to do it. My problem is that the end users do not have the required permissions to query the `pg_` tables of their db so I don't know where I would find the schema information. Maybe there's a solution I'm missing though. Do you have an idea of how we could get the schema information?

**Comment by porteron** [comment]
Without access to the `pg_` tables I do not think there is a way. I guess you could have them do a `select * from <table> limit 1` then have them copy that into prompt that is included in the postMessage. Probably will also need to update the prompt in the code to explain what that indicates. I'm fortunate enough to have access to the schema info so I can probably do something similar by copy/pasting the schema info.

**Comment by RobinPicard** [comment]
Hi @porteron. I thought more about it and actually it's possible as the Metabase frontend does have access to this information to fill out the "learn about your data" panel. By doing api requests similar to those that happen when clicking on the little icons on the right of the screen we get the all the information we need. I used sentence embeddings afterward to try to include relevant context info regarding the database in the prompt sent to chatgpt. I'm really not an expert in AI topics though. Tell me what you think about it if you have some time to take a look!

I've created a draft PR with what I've been trying out: https://github.com/RobinPicard/metabase-chatgpt/pull/9

**Comment by RobinPicard** [comment]
I finished writing the PR mentioned for this new feature. The result looks pretty nice imo

Would you mind testing it on Metabase Cloud if you have access to it @porteron? I changed job since I first worked on the extension so now I can only run Metabase locally. I would just like that to make sure that the requests to the Metabase API go through and that the creation of the embeddings works with a larger database (the demo one provided by Metabase includes only 8 tables)

https://github.com/RobinPicard/metabase-chatgpt/assets/83579270/6cb6a5e8-588d-4000-847a-75cc51cc18ba

**Comment by porteron** [comment]
Looks great, you added a lot of code in PR #9. I need to review it further before I can run against my instance of Metabase. 
The new prompts you added look better too. The results in your video are great!

**Comment by RobinPicard** [comment]
Thanks a lot for taking the time to look at it! I think there are still 3 issues (although maybe they can be dealt with in a further PR if at all):
- retrieving data about the database structure through API calls can take a long time as it's one request per table
- the creation of the embeddings makes the browser laggy (but at least it's not frozen thanks to doing it in batch)
- including context about only 3 tables is not enough for databases with many tables + we may reach maximum token limits if there are tables with a very high number of columns with descriptions (maybe we could have the number of tables included in the context depend on the character length of the sentences describing each of them?)

**Comment by RobinPicard** [comment]
I merged the PR as I got the chance to test it on a larger database and everything went alright. Thanks again for the suggestion
